
#
# Super simple example of a Dockerfile
#
FROM ubuntu:latest
MAINTAINER zixia zhen "zhenzixia@gmail.com"

#RUN apt-get update
#RUN apt-get install -y python python-pip wget
#RUN pip install Flask

ADD controller /usr/local/bin

#EXPOSE 8080

WORKDIR /home